[workspace]
members = [
  "faer-entity",
  "faer-core",
  "faer-cholesky",
  "faer-lu",
  "faer-qr",
  "faer-svd",
  "faer-evd",

  "faer-sparse-experimental",

  "faer",
]
exclude = ["faer-bench"]
resolver = "2"

[workspace.dependencies]
coe-rs = "0.1"
reborrow = "0.5"
dyn-stack = { version = "0.10", default-features = false }
pulp = { version = "0.16", default-features = false }

num-traits = { version = "0.2", default-features = false }
num-complex = { version = "0.4", default-features = false }
libm = "0.2"
bytemuck = { version = "1", default-features = false }

rayon = "1"
assert2 = "0.3"
log = { version = "0.4", default-features = false }

criterion = { git = "https://github.com/sarah-ek/criterion.rs" }

[profile.dev]
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.bench]
inherits = "release"
debug = true
