[workspace]
members = [
  "faer-core",
  "faer-cholesky",
  "faer-lu",
  "faer-qr",
  "faer-svd",
  "faer-evd",
]
exclude = ["faer-bench"]

[workspace.dependencies]
coe-rs = "0.1"
reborrow = "0.5"
dyn-stack = "0.9"
assert2 = "0.3"
num-traits = "0.2"
num-complex = "0.4.3"
rayon = "1.7"
# pulp = { version = "0.13", default-features = false }
pulp = { git = "https://github.com/sarah-ek/pulp.git", default-features = false }
bytemuck = "1"

[profile.dev]
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false
