[package]
name = "faer-macros"
version = "0.21.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.79", features = ["extra-traits", "printing", "visit", "visit-mut", "full"] }
