[package]
name = "faer-core"
version = "0.3.0"
edition = "2021"
authors = ["sarah <>"]
description = "Basic linear algebra routines"
readme = "../README.md"
repository = "https://github.com/sarah-ek/faer-rs/"
license = "MIT"
keywords = ["math", "matrix", "linear-algebra"]

[dependencies]
gemm = { version = "0.13", default-features = false, features = ["rayon"] }
pulp = { version = "0.10", default-features = false }
reborrow = "0.5"
dyn-stack = "0.8"
assert2 = "0.3"
num-traits = "0.2"
num-complex = "0.4"
aligned-vec = "0.5"
rayon = "1.6"
seq-macro = "0.3"

[features]
default = ["std"]
std = ["gemm/std", "pulp/std"]
nightly = ["gemm/nightly", "pulp/nightly"]

[dev-dependencies]
criterion = "0.4"
rand = "0.8.5"
nalgebra = "0.31.4"
assert_approx_eq = "1.1.0"

[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex-header.html"]
