[par]
seq = true
rayon = true

[decomp]
shapes = [
  128,
  256,
  512,
  1024,
  2048,
  3072,
  4096,
  5120,
]

[block_decomp]
shapes = [
  128,
  256,
  512,
  1024,
  2048,
  3072,
  4096,
  5120,
  6144,
  7168,
  8192,
  9216,
  10240,
]
  
[svd]
shapes = [
  128,
  256,
  512,
  1024,
  2048,
  3072,
  4096,
  5120,
]

[evd]
shapes = [
  128,
  256,
  512,
  1024,
  2048,
  3072,
  4096,
  5120,
]
