[par]
seq = true
rayon = true

[decomp]
shapes = [
  [128, 128],
  [256, 256],
  [1024, 1024],
  [512, 512],
  [2048, 2048],
  [3072, 3072],
  [4096, 4096],
]

[block_decomp]
shapes = [
  [128, 128],
  [256, 256],
  [1024, 1024],
  [512, 512],
  [2048, 2048],
  [3072, 3072],
  [4096, 4096],
]
  
[svd]
shapes = [
  [128, 128],
  [256, 256],
  [1024, 1024],
  [512, 512],
  [2048, 2048],
  [3072, 3072],
  [4096, 4096],
]

[evd]
shapes = [
  [128, 128],
  [256, 256],
  [1024, 1024],
  [512, 512],
  [2048, 2048],
  [3072, 3072],
  [4096, 4096],
]
