on:
  push:
    branches:
      - main
      - refactor-3
  pull_request:

name: Run Tests

jobs:
  msrv:
    name: msrv-${{ matrix.toolchain }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.84.0
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: MSRV 1.84.0
        run:
          cd ./faer-traits &&
          cargo check &&
          cd ../faer &&
          cargo check

  nostd:
    name: nostd-${{ matrix.toolchain }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - nightly-2025-01-08
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: nostd
        run:
          cd ./faer-no-std-test &&
          cargo run --profile nostd

  testing:
    name: testing-${{ matrix.toolchain }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: Install latest nextest
        uses: taiki-e/install-action@nextest

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install OpenBLAS by apt
        run: |
          sudo apt update
          sudo apt install -y libopenblas-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Install OpenBLAS by vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git --depth 1
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg.exe install openblas:x64-windows
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Collect coverage data
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        run: cd faer && cargo llvm-cov nextest --features=unstable --lcov --output-path ../lcov.info

      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
